# Generated by Django 4.2.3 on 2023-09-03 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupCharacterSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupDigit', models.IntegerField(blank=True, default=0, null=True)),
                ('groupClass', models.CharField(blank=True, max_length=200, null=True)),
                ('groupRPG', models.IntegerField(blank=True, default=0, null=True)),
                ('groupDiceLeft', models.IntegerField(blank=True, default=5, null=True)),
                ('groupDiceLastRoll', models.IntegerField(blank=True, default=0, null=True)),
                ('groupResistancePrice', models.IntegerField(blank=True, default=0, null=True)),
                ('groupFlex', models.IntegerField(blank=True, default=0, null=True)),
                ('groupMaxPurchase', models.IntegerField(blank=True, default=0, null=True)),
                ('groupDelivery', models.IntegerField(blank=True, default=0, null=True)),
                ('groupUnits', models.IntegerField(blank=True, default=0, null=True)),
                ('groupImportance', models.IntegerField(blank=True, default=0, null=True)),
                ('groupQuality', models.IntegerField(blank=True, default=0, null=True)),
                ('groupRole', models.IntegerField(blank=True, default=0, null=True)),
                ('groupBasePrice', models.IntegerField(blank=True, default=0, null=True)),
                ('groupBaseUnits', models.IntegerField(blank=True, default=0, null=True)),
                ('groupNote', models.CharField(default='Note.', max_length=200)),
            ],
            options={
                'verbose_name': 'Group Login',
                'verbose_name_plural': 'Group Login',
            },
        ),
    ]
