# Generated by Django 4.2.3 on 2023-09-11 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diceroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupcharactersheet',
            options={'verbose_name': 'Group Character Sheet', 'verbose_name_plural': 'Group Character Sheet'},
        ),
    ]
