# Generated by Django 4.2.3 on 2023-08-02 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher', models.CharField(help_text='Prof. John Doe', max_length=200)),
                ('className', models.CharField(help_text='NTU_Negotiation_2023_2', max_length=200)),
                ('created', models.DateField(auto_now_add=True)),
                ('lastUpdate', models.DateField()),
                ('numberOfGroups', models.IntegerField()),
                ('numberOfMembers', models.IntegerField()),
                ('diceHigh', models.IntegerField(help_text='sugested min=10 max=28; All dice=48')),
                ('diceLow', models.IntegerField()),
                ('round1_start', models.DateTimeField()),
                ('round1_end', models.DateTimeField()),
                ('round2_start', models.DateTimeField()),
                ('round2_end', models.DateTimeField()),
                ('round3_start', models.DateTimeField()),
                ('round3_end', models.DateTimeField()),
                ('round4_start', models.DateTimeField()),
                ('round4_end', models.DateTimeField()),
                ('round5_start', models.DateTimeField()),
                ('round5_end', models.DateTimeField()),
                ('round6_start', models.DateTimeField()),
                ('round6_end', models.DateTimeField()),
                ('round7_start', models.DateTimeField()),
                ('round7_end', models.DateTimeField()),
                ('round8_start', models.DateTimeField()),
                ('round8_end', models.DateTimeField()),
                ('round9_start', models.DateTimeField()),
                ('round9_end', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='GameTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GameGroupNumber', models.IntegerField()),
            ],
        ),
    ]
