# Generated by Django 4.2.3 on 2023-08-02 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameSetup', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gametest',
            old_name='GameGroupNumber',
            new_name='gameGroupNumber',
        ),
        migrations.AddField(
            model_name='gametest',
            name='gameGroupComment',
            field=models.CharField(default='TESTING', max_length=200),
            preserve_default=False,
        ),
    ]
