# Generated by Django 4.2.3 on 2023-08-02 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameSetup', '0002_rename_gamegroupnumber_gametest_gamegroupnumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gametest',
            name='gameGroupNumber',
            field=models.CharField(max_length=200),
        ),
    ]
