# Generated by Django 4.2.3 on 2023-08-03 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameSetup', '0003_alter_gametest_gamegroupnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='gametest',
            name='gameGroupDigit',
            field=models.IntegerField(null=True),
        ),
    ]
