# Generated by Django 4.2.3 on 2023-08-05 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameSetup', '0004_gametest_gamegroupdigit'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupComment', models.CharField(max_length=100)),
                ('groupPassword', models.CharField(max_length=20)),
                ('groupDigit', models.IntegerField(null=True)),
                ('groupTeacher', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Group Login',
                'verbose_name_plural': 'Group Login',
            },
        ),
        migrations.AlterModelOptions(
            name='gametest',
            options={'verbose_name': 'Game Test Clyde', 'verbose_name_plural': 'Game Test Clyde'},
        ),
    ]
