# Generated by Django 4.2.3 on 2023-08-07 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameSetup', '0005_grouplogin_alter_gametest_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouplogin',
            name='groupTeacher',
            field=models.CharField(max_length=200),
        ),
    ]
