# Generated by Django 4.2.3 on 2023-08-09 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameSetup', '0007_remove_gamesettings_round1_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesettings',
            name='round0End',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='gamesettings',
            name='round0ProductCurrency',
            field=models.CharField(help_text='NTD', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='gamesettings',
            name='round0ProductName',
            field=models.CharField(help_text='Pet Feeder', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='gamesettings',
            name='round0ProductPrice',
            field=models.DecimalField(decimal_places=2, help_text='320', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='gamesettings',
            name='round0ProductUnits',
            field=models.IntegerField(help_text='6000', null=True),
        ),
        migrations.AddField(
            model_name='gamesettings',
            name='round0Start',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='gamesettings',
            name='round2ProductCurrency',
            field=models.CharField(help_text='NTD', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='gamesettings',
            name='round2ProductName',
            field=models.CharField(help_text='Winter Ear Muffs', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='gamesettings',
            name='round2ProductPrice',
            field=models.DecimalField(decimal_places=2, help_text='250', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='gamesettings',
            name='round2ProductUnits',
            field=models.IntegerField(help_text='10000', null=True),
        ),
        migrations.AddField(
            model_name='gamesettings',
            name='round3ProductCurrency',
            field=models.CharField(help_text='NTD', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='gamesettings',
            name='round3ProductName',
            field=models.CharField(help_text='Foldable Pet Carrier', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='gamesettings',
            name='round3ProductPrice',
            field=models.DecimalField(decimal_places=2, help_text='7500', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='gamesettings',
            name='round3ProductUnits',
            field=models.IntegerField(help_text='1200', null=True),
        ),
        migrations.AddField(
            model_name='gamesettings',
            name='round4ProductCurrency',
            field=models.CharField(help_text='USD', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='gamesettings',
            name='round4ProductName',
            field=models.CharField(help_text='LED Christmas Tree', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='gamesettings',
            name='round4ProductPrice',
            field=models.DecimalField(decimal_places=2, help_text='1200', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='gamesettings',
            name='round4ProductUnits',
            field=models.IntegerField(help_text='6500', null=True),
        ),
        migrations.AddField(
            model_name='gamesettings',
            name='round5ProductCurrency',
            field=models.CharField(help_text='USD', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='gamesettings',
            name='round5ProductName',
            field=models.CharField(help_text='Abdominal Exercise Equipment', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='gamesettings',
            name='round5ProductPrice',
            field=models.DecimalField(decimal_places=2, help_text='6.5', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='gamesettings',
            name='round5ProductUnits',
            field=models.IntegerField(help_text='11000', null=True),
        ),
        migrations.AddField(
            model_name='gamesettings',
            name='round6ProductCurrency',
            field=models.CharField(help_text='NTD', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='gamesettings',
            name='round6ProductName',
            field=models.CharField(help_text='Color LED Calendar', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='gamesettings',
            name='round6ProductPrice',
            field=models.DecimalField(decimal_places=2, help_text='1600', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='gamesettings',
            name='round6ProductUnits',
            field=models.IntegerField(help_text='1200', null=True),
        ),
        migrations.AddField(
            model_name='gamesettings',
            name='round7ProductCurrency',
            field=models.CharField(help_text='USD', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='gamesettings',
            name='round7ProductName',
            field=models.CharField(help_text='The Lil Hombre Two-in-one', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='gamesettings',
            name='round7ProductPrice',
            field=models.DecimalField(decimal_places=2, help_text='3060', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='gamesettings',
            name='round7ProductUnits',
            field=models.IntegerField(help_text='1800', null=True),
        ),
        migrations.AddField(
            model_name='gamesettings',
            name='round8ProductCurrency',
            field=models.CharField(help_text='USD', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='gamesettings',
            name='round8ProductName',
            field=models.CharField(help_text='Kitchen Make Believe', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='gamesettings',
            name='round8ProductPrice',
            field=models.DecimalField(decimal_places=2, help_text='10.5', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='gamesettings',
            name='round8ProductUnits',
            field=models.IntegerField(help_text='10850', null=True),
        ),
        migrations.AddField(
            model_name='gamesettings',
            name='round9ProductCurrency',
            field=models.CharField(help_text='USD', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='gamesettings',
            name='round9ProductName',
            field=models.CharField(help_text='Sports Carry Duffle Bag', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='gamesettings',
            name='round9ProductPrice',
            field=models.DecimalField(decimal_places=2, help_text='1450', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='gamesettings',
            name='round9ProductUnits',
            field=models.IntegerField(help_text='3800', null=True),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='round1ProductName',
            field=models.CharField(help_text='Baby Car Seat', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='round1ProductPrice',
            field=models.DecimalField(decimal_places=2, help_text='1450', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='round1ProductUnits',
            field=models.IntegerField(help_text='1000', null=True),
        ),
    ]
