# Generated by Django 4.2.3 on 2023-08-12 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameSetup', '0008_gamesettings_round0end_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamesettings',
            options={'verbose_name': 'Game Settings', 'verbose_name_plural': 'Game Settings'},
        ),
        migrations.AddField(
            model_name='gamesettings',
            name='playDays',
            field=models.IntegerField(blank=True, default='5', help_text='5'),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='className',
            field=models.CharField(default='NTU_Negotiation_2023_2', help_text='NTU_Negotiation_2023_2', max_length=200),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='diceHigh',
            field=models.IntegerField(blank=True, default='28', help_text='sugested min=10 max=28; All dice=48'),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='diceLow',
            field=models.IntegerField(blank=True, default='10', help_text='10'),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='lastUpdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='numberOfGroups',
            field=models.IntegerField(blank=True, default='50'),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='numberOfMembers',
            field=models.IntegerField(blank=True, default='3'),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='round0End',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='round0ProductCurrency',
            field=models.CharField(blank=True, default='NTD', help_text='NTD', max_length=50),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='round0ProductName',
            field=models.CharField(blank=True, default='Pet Feeder', help_text='Pet Feeder', max_length=200),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='round0ProductPrice',
            field=models.DecimalField(blank=True, decimal_places=2, default='320', help_text='320', max_digits=10),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='round0ProductUnits',
            field=models.IntegerField(blank=True, default='6000', help_text='6000'),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='round0Start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='round1End',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='round1ProductCurrency',
            field=models.CharField(blank=True, default='NTD', help_text='NTD', max_length=50),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='round1ProductName',
            field=models.CharField(blank=True, default='Baby Car Seat', help_text='Baby Car Seat', max_length=200),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='round1ProductPrice',
            field=models.DecimalField(blank=True, decimal_places=2, default='1450', help_text='1450', max_digits=10),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='round1ProductUnits',
            field=models.IntegerField(blank=True, default='1000', help_text='1000'),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='round1Start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='round2End',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='round2ProductCurrency',
            field=models.CharField(blank=True, default='NTD', help_text='NTD', max_length=50),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='round2ProductName',
            field=models.CharField(blank=True, default='Winter Ear Muffs', help_text='Winter Ear Muffs', max_length=200),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='round2ProductPrice',
            field=models.DecimalField(blank=True, decimal_places=2, default='250', help_text='250', max_digits=10),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='round2ProductUnits',
            field=models.IntegerField(blank=True, default='10000', help_text='10000'),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='round2Start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='round3End',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='round3ProductCurrency',
            field=models.CharField(blank=True, default='NTD', help_text='NTD', max_length=50),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='round3ProductName',
            field=models.CharField(blank=True, default='Foldable Pet Carrier', help_text='Foldable Pet Carrier', max_length=200),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='round3ProductPrice',
            field=models.DecimalField(blank=True, decimal_places=2, default='7500', help_text='7500', max_digits=10),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='round3ProductUnits',
            field=models.IntegerField(blank=True, default='1200', help_text='1200'),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='round3Start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='round4End',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='round4ProductCurrency',
            field=models.CharField(blank=True, default='USD', help_text='USD', max_length=50),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='round4ProductName',
            field=models.CharField(blank=True, default='LED Christmas Tree', help_text='LED Christmas Tree', max_length=200),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='round4ProductPrice',
            field=models.DecimalField(blank=True, decimal_places=2, default='1200', help_text='1200', max_digits=10),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='round4ProductUnits',
            field=models.IntegerField(blank=True, default='6500', help_text='6500'),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='round4Start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='round5End',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='round5ProductCurrency',
            field=models.CharField(blank=True, default='USD', help_text='USD', max_length=50),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='round5ProductName',
            field=models.CharField(blank=True, default='Abdominal Exercise Equipment', help_text='Abdominal Exercise Equipment', max_length=200),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='round5ProductPrice',
            field=models.DecimalField(blank=True, decimal_places=2, default='6.5', help_text='6.5', max_digits=10),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='round5ProductUnits',
            field=models.IntegerField(blank=True, default='11000', help_text='11000'),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='round5Start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='round6End',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='round6ProductCurrency',
            field=models.CharField(blank=True, default='NTD', help_text='NTD', max_length=50),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='round6ProductName',
            field=models.CharField(blank=True, default='Color LED Calendar', help_text='Color LED Calendar', max_length=200),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='round6ProductPrice',
            field=models.DecimalField(blank=True, decimal_places=2, default='1600', help_text='1600', max_digits=10),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='round6ProductUnits',
            field=models.IntegerField(blank=True, default='1200', help_text='1200'),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='round6Start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='round7End',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='round7ProductCurrency',
            field=models.CharField(blank=True, default='USD', help_text='USD', max_length=50),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='round7ProductName',
            field=models.CharField(blank=True, default='The Lil Hombre Two-in-one', help_text='The Lil Hombre Two-in-one', max_length=200),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='round7ProductPrice',
            field=models.DecimalField(blank=True, decimal_places=2, default='3060', help_text='3060', max_digits=10),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='round7ProductUnits',
            field=models.IntegerField(blank=True, default='1800', help_text='1800'),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='round7Start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='round8End',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='round8ProductCurrency',
            field=models.CharField(blank=True, default='USD', help_text='USD', max_length=50),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='round8ProductName',
            field=models.CharField(blank=True, default='Kitchen Make Believe', help_text='Kitchen Make Believe', max_length=200),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='round8ProductPrice',
            field=models.DecimalField(blank=True, decimal_places=2, default='10.5', help_text='10.5', max_digits=10),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='round8ProductUnits',
            field=models.IntegerField(blank=True, default='10850', help_text='10850'),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='round8Start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='round9End',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='round9ProductCurrency',
            field=models.CharField(blank=True, default='USD', help_text='USD', max_length=50),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='round9ProductName',
            field=models.CharField(blank=True, default='Sports Carry Duffle Bag', help_text='Sports Carry Duffle Bag', max_length=200),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='round9ProductPrice',
            field=models.DecimalField(blank=True, decimal_places=2, default='1450', help_text='1450', max_digits=10),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='round9ProductUnits',
            field=models.IntegerField(blank=True, default='3800', help_text='3800'),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='round9Start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='teacher',
            field=models.CharField(default='Prof. Clyde Warden', help_text='Prof. Clyde Warden', max_length=200),
        ),
        migrations.AlterField(
            model_name='gametest',
            name='gameGroupDigit',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='grouplogin',
            name='groupDigit',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
