# Generated by Django 4.2.3 on 2023-08-12 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameSetup', '0009_alter_gamesettings_options_gamesettings_playdays_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesettings',
            name='teacherNotes',
            field=models.TextField(blank=True, default='Your notes here', help_text='Only seen by instructor'),
        ),
    ]
