# Generated by Django 4.2.3 on 2023-08-13 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameSetup', '0010_gamesettings_teachernotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouplogin',
            name='groupClass',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='grouplogin',
            name='groupDigit',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
