# Generated by Django 4.2.5 on 2023-10-26 12:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameSetup', '0011_grouplogin_groupclass_alter_grouplogin_groupdigit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesettings',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='lastUpdate',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='numberOfGroups',
            field=models.IntegerField(blank=True, default=50),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='numberOfMembers',
            field=models.IntegerField(blank=True, default=3),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='round0End',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 26, 17, 38, 2, 847933, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='round0ProductCurrency',
            field=models.CharField(default='NTD', help_text='NTD', max_length=50),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='round0ProductName',
            field=models.CharField(default='Pet Feeder', help_text='Pet Feeder', max_length=200),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='round0ProductPrice',
            field=models.DecimalField(decimal_places=2, default='320', help_text='320', max_digits=10),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='round0ProductUnits',
            field=models.IntegerField(default='6000', help_text='6000'),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='round0Start',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 26, 12, 38, 2, 847726, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='round1End',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 2, 17, 38, 2, 847968, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='round1Start',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 2, 12, 38, 2, 847943, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='round2End',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 9, 17, 38, 2, 848001, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='round2Start',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 9, 12, 38, 2, 847975, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='round3End',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 16, 17, 38, 2, 848030, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='round3Start',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 16, 12, 38, 2, 848007, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='round4End',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 23, 17, 38, 2, 848059, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='round4Start',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 23, 12, 38, 2, 848037, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='round5End',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 30, 17, 38, 2, 848088, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='round5Start',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 30, 12, 38, 2, 848064, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='round6End',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 7, 17, 38, 2, 848113, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='round6Start',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 7, 12, 38, 2, 848093, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='round7End',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 14, 17, 38, 2, 848138, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='round7Start',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 14, 12, 38, 2, 848118, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='round8End',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 21, 17, 38, 2, 848162, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='round8Start',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 21, 12, 38, 2, 848143, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='round9End',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 28, 17, 38, 2, 848187, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='round9Start',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 28, 12, 38, 2, 848168, tzinfo=datetime.timezone.utc)),
        ),
    ]
