# Generated by Django 4.2.5 on 2023-11-18 13:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameSetup', '0017_gamesettings_classslides_gamesettings_ebook_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesettings',
            name='round0End',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 18, 18, 0, 9, 606400, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='round0ProductName',
            field=models.CharField(default='<a href="https://drive.google.com/open?id=1erZQh-xTOjtuajoRr4pIa030z3d2729d" target="_blank">Pet Feeder</a>', help_text='Pet Feeder', max_length=1000),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='round0Start',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 18, 14, 0, 9, 606344, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='round1End',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 25, 18, 0, 9, 606533, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='round1ProductName',
            field=models.CharField(default='<a href="https://drive.google.com/open?id=11sKz1NUVK_HOIUZYTRbtLEvxCYmSKlsi" target="_blank">Baby Car Seat</a>', help_text='Baby Car Seat', max_length=1000),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='round1Start',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 25, 13, 0, 9, 606409, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='round2End',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 2, 18, 0, 9, 606577, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='round2ProductName',
            field=models.CharField(default='<a href="https://drive.google.com/open?id=1aM1oXLHkLi2t1Vj31dEQuOpkVTfOSwHN" target="_blank">Winter Ear Muffs</a>', help_text='Winter Ear Muffs', max_length=1000),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='round2Start',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 2, 13, 0, 9, 606544, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='round3End',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 9, 18, 0, 9, 606612, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='round3ProductName',
            field=models.CharField(default='<a href="https://drive.google.com/open?id=1wdj2VZ2qnsZp5ahswQrr7GX5--xtgFTJ" target="_blank">Foldable Pet Carrier</a>', help_text='Foldable Pet Carrier', max_length=1000),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='round3Start',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 9, 13, 0, 9, 606585, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='round4End',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 16, 18, 0, 9, 606648, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='round4ProductName',
            field=models.CharField(default='<a href="https://drive.google.com/open?id=15YnZ__lkJNBIZpJ6TtJEAJ6CNEODtVKC" target="_blank">LED Christmas Tree</a>', help_text='LED Christmas Tree', max_length=1000),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='round4Start',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 16, 13, 0, 9, 606619, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='round5End',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 23, 18, 0, 9, 606679, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='round5ProductName',
            field=models.CharField(default='<a href="https://drive.google.com/open?id=1utnjF1_hnfFqPKYIOMoBKeyHfdbpHCGu" target="_blank">Abdominal Exercise Equipment</a>', help_text='Abdominal Exercise Equipment', max_length=1000),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='round5Start',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 23, 13, 0, 9, 606654, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='round6End',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 30, 18, 0, 9, 606712, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='round6ProductName',
            field=models.CharField(default='<a href="https://drive.google.com/open?id=1NU3l9HVZEXi5YR2Dmx7hqyqtJi6LBcHu" target="_blank">Color LED Calendar</a>', help_text='Color LED Calendar', max_length=1000),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='round6Start',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 30, 13, 0, 9, 606686, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='round7End',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 6, 18, 0, 9, 606740, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='round7ProductName',
            field=models.CharField(default='<a href="https://drive.google.com/open?id=1sWk_oR9vXUPTjO34Ijk4CZH0MrHiffuf" target="_blank">The Lil Hombre Two-in-one</a>', help_text='The Lil Hombre Two-in-one', max_length=1000),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='round7Start',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 6, 13, 0, 9, 606717, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='round8End',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 13, 18, 0, 9, 606768, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='round8ProductName',
            field=models.CharField(default='<a href="https://drive.google.com/open?id=1qYi-CgHhDHDb5zrscqxtB6jNRqSl1bxW" target="_blank">Kitchen Make Believe</a>', help_text='Kitchen Make Believe', max_length=1000),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='round8Start',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 13, 13, 0, 9, 606746, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='round9End',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 20, 18, 0, 9, 606799, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='round9ProductName',
            field=models.CharField(default='<a href="https://drive.google.com/open?id=1Iv_w-HHZyn6-rFt77KT6peO2ZxzZ0rUT" target="_blank">Sports Carry Duffle Bag</a>', help_text='Sports Carry Duffle Bag', max_length=1000),
        ),
        migrations.AlterField(
            model_name='gamesettings',
            name='round9Start',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 20, 13, 0, 9, 606774, tzinfo=datetime.timezone.utc)),
        ),
    ]
