# Generated by Django 4.2.3 on 2023-09-11 08:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='responses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupDigit', models.IntegerField(blank=True, default=0, null=True)),
                ('groupClass', models.CharField(blank=True, max_length=200, null=True)),
                ('groupRPG', models.IntegerField(blank=True, default=0, null=True)),
                ('dealDateStamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('dealDealID', models.IntegerField(blank=True, default=0, null=True)),
                ('dealCounterpart', models.IntegerField(blank=True, default=0, null=True)),
                ('dealBuySell', models.IntegerField(blank=True, default=0, null=True)),
                ('dealUnits', models.IntegerField(blank=True, default=0, null=True)),
                ('dealPrice', models.IntegerField(blank=True, default=0, null=True)),
                ('dealQuality', models.IntegerField(blank=True, default=0, null=True)),
                ('dealDelivery', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'verbose_name': 'Deal Responses',
                'verbose_name_plural': 'Deal Responses',
            },
        ),
    ]
