# Generated by Django 4.2.3 on 2023-09-17 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0004_gifting_messaging'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gifting',
            old_name='giftSubject',
            new_name='giftMessage',
        ),
    ]
