# Generated by Django 4.2.5 on 2023-10-24 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0005_rename_giftsubject_gifting_giftmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gifting',
            name='giftMessage',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='messaging',
            name='messageSubject',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
