# Generated by Django 4.2.5 on 2023-11-23 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveysection',
            name='code',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='surveysection',
            name='code_order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
