# Generated by Django 4.2.5 on 2023-11-24 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_rename_order_surveyquestion_question_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyquestion',
            name='section_code',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
