# Generated by Django 4.2.5 on 2023-11-25 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_surveyquestion_section_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userresponse',
            name='user',
        ),
        migrations.AddField(
            model_name='userresponse',
            name='student_id',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
