# Generated by Django 4.2.5 on 2023-11-25 07:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_remove_userresponse_user_userresponse_student_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userresponse',
            name='language',
        ),
        migrations.AddField(
            model_name='userresponse',
            name='dateStamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
