# Generated by Django 4.2.5 on 2023-11-26 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_remove_userresponse_language_userresponse_datestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresponse',
            name='groupClass',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
